/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTransacoesRouteImport } from './routes/app.transacoes'
import { Route as AppOrcamentosRouteImport } from './routes/app.orcamentos'
import { Route as AppMetasRouteImport } from './routes/app.metas'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppContasRouteImport } from './routes/app.contas'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppCategoriasRouteImport } from './routes/app.categorias'
import { Route as ApiInsightsGenerateRouteImport } from './routes/api.insights.generate'
import { Route as ApiDocumentsProcessRouteImport } from './routes/api.documents.process'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransacoesRoute = AppTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosRoute = AppOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppContasRoute = AppContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const ApiInsightsGenerateRoute = ApiInsightsGenerateRouteImport.update({
  id: '/api/insights/generate',
  path: '/api/insights/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsProcessRoute = ApiDocumentsProcessRouteImport.update({
  id: '/api/documents/process',
  path: '/api/documents/process',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contas': typeof AppContasRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/metas': typeof AppMetasRoute
  '/app/orcamentos': typeof AppOrcamentosRoute
  '/app/transacoes': typeof AppTransacoesRoute
  '/app/': typeof AppIndexRoute
  '/api/documents/process': typeof ApiDocumentsProcessRoute
  '/api/insights/generate': typeof ApiInsightsGenerateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contas': typeof AppContasRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/metas': typeof AppMetasRoute
  '/app/orcamentos': typeof AppOrcamentosRoute
  '/app/transacoes': typeof AppTransacoesRoute
  '/app': typeof AppIndexRoute
  '/api/documents/process': typeof ApiDocumentsProcessRoute
  '/api/insights/generate': typeof ApiInsightsGenerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contas': typeof AppContasRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/metas': typeof AppMetasRoute
  '/app/orcamentos': typeof AppOrcamentosRoute
  '/app/transacoes': typeof AppTransacoesRoute
  '/app/': typeof AppIndexRoute
  '/api/documents/process': typeof ApiDocumentsProcessRoute
  '/api/insights/generate': typeof ApiInsightsGenerateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/categorias'
    | '/app/configuracoes'
    | '/app/contas'
    | '/app/insights'
    | '/app/metas'
    | '/app/orcamentos'
    | '/app/transacoes'
    | '/app/'
    | '/api/documents/process'
    | '/api/insights/generate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/categorias'
    | '/app/configuracoes'
    | '/app/contas'
    | '/app/insights'
    | '/app/metas'
    | '/app/orcamentos'
    | '/app/transacoes'
    | '/app'
    | '/api/documents/process'
    | '/api/insights/generate'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/categorias'
    | '/app/configuracoes'
    | '/app/contas'
    | '/app/insights'
    | '/app/metas'
    | '/app/orcamentos'
    | '/app/transacoes'
    | '/app/'
    | '/api/documents/process'
    | '/api/insights/generate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiDocumentsProcessRoute: typeof ApiDocumentsProcessRoute
  ApiInsightsGenerateRoute: typeof ApiInsightsGenerateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transacoes': {
      id: '/app/transacoes'
      path: '/transacoes'
      fullPath: '/app/transacoes'
      preLoaderRoute: typeof AppTransacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orcamentos': {
      id: '/app/orcamentos'
      path: '/orcamentos'
      fullPath: '/app/orcamentos'
      preLoaderRoute: typeof AppOrcamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/metas': {
      id: '/app/metas'
      path: '/metas'
      fullPath: '/app/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contas': {
      id: '/app/contas'
      path: '/contas'
      fullPath: '/app/contas'
      preLoaderRoute: typeof AppContasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categorias': {
      id: '/app/categorias'
      path: '/categorias'
      fullPath: '/app/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/insights/generate': {
      id: '/api/insights/generate'
      path: '/api/insights/generate'
      fullPath: '/api/insights/generate'
      preLoaderRoute: typeof ApiInsightsGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/process': {
      id: '/api/documents/process'
      path: '/api/documents/process'
      fullPath: '/api/documents/process'
      preLoaderRoute: typeof ApiDocumentsProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContasRoute: typeof AppContasRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppMetasRoute: typeof AppMetasRoute
  AppOrcamentosRoute: typeof AppOrcamentosRoute
  AppTransacoesRoute: typeof AppTransacoesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriasRoute: AppCategoriasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContasRoute: AppContasRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppMetasRoute: AppMetasRoute,
  AppOrcamentosRoute: AppOrcamentosRoute,
  AppTransacoesRoute: AppTransacoesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiDocumentsProcessRoute: ApiDocumentsProcessRoute,
  ApiInsightsGenerateRoute: ApiInsightsGenerateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
